name: cobs
description: A Dart implementation of the Consistent Overhead Byte Stuffing (COBS) algorithm.
version: 0.1.0
author: Jim Shepherd <jeshep@gmail.com>
homepage: https://github.com/jimshepherd/cobs-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

dev_dependencies:
  test:
  collection: ^1.14.11

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
